apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-deployment
spec:
  selector:
    matchLabels:
      app: matches-app
  replicas: 1
  template:
    metadata:
      labels:
        app: matches-app
    spec:
      containers: 
        - name: matches-app
          image: evantz/devops:lab4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  